name: Bats
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  unit-test:
    runs-on: ubuntu-latest
    name: Bats
    steps:
    - uses: actions/checkout@v2

    - name: install bats
      run: |
        git clone --depth=1 https://github.com/bats-core/bats-core.git

    - name: run tests
      run: bats-core/bin/bats ./tests.bat
